<?php

// THIS IS IMPORTANT
//
// Remember to remove the encapsulating `if` statement
// from the ACF PHP export
//

acf_add_local_field_group(array(
	'key' => 'group_5e80d898b45f4',
	'title' => 'About',
	'fields' => array(
		array(
			'key' => 'field_5e80d975f7285',
			'label' => 'Subtitle',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e80dd827a7e6',
			'label' => 'Personality Traits',
			'name' => 'personality_traits',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5e80ddb97a7e7',
					'label' => 'Test Name',
					'name' => 'test_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Myers-Briggs',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e80ddfa7a7e8',
					'label' => 'Test Link',
					'name' => 'test_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e80de0e7a7e9',
					'label' => 'Answer',
					'name' => 'answer',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'ENTP',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e80de3d7a7ea',
					'label' => 'Answer Link',
					'name' => 'answer_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5e80db80f7286',
			'label' => 'Work History',
			'name' => 'work_history',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5e80db9df7287',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Job',
			'sub_fields' => array(
				array(
					'key' => 'field_5e80db9df7287',
					'label' => 'Company',
					'name' => 'company',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e80dbabf7288',
					'label' => 'Website',
					'name' => 'website',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e80dbb8f7289',
					'label' => 'Job Title',
					'name' => 'job_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e80dbe3f728a',
					'label' => 'Job Description',
					'name' => 'job_description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5e80dc09f728b',
					'label' => 'Start Date',
					'name' => 'start_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
				),
				array(
					'key' => 'field_5e80dc52f728c',
					'label' => 'End Date',
					'name' => 'end_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
				),
			),
		),
		array(
			'key' => 'field_5e80dca97a7e2',
			'label' => 'Education',
			'name' => 'education',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5e80dcbd7a7e3',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add School',
			'sub_fields' => array(
				array(
					'key' => 'field_5e80dcbd7a7e3',
					'label' => 'School Name',
					'name' => 'school_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e80dcda7a7e4',
					'label' => 'School Website',
					'name' => 'school_website',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e80dd5d7a7e5',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5f5d6c333682a',
					'label' => 'Start Date',
					'name' => 'start_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
				),
				array(
					'key' => 'field_5f5d6c553682b',
					'label' => 'End Date',
					'name' => 'end_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '11',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5f5d6ceb41bc6',
	'title' => 'Downloads',
	'fields' => array(
		array(
			'key' => 'field_5f5d6d096c6d4',
			'label' => 'Downloads',
			'name' => 'downloads',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5f7a47d6c1b44',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Card',
			'sub_fields' => array(
				array(
					'key' => 'field_5f5d6d3c6c6d5',
					'label' => 'Card Layout',
					'name' => 'layout',
					'type' => 'radio',
					'instructions' => 'Vertical: Image on top<br/>
Horizontal: Image on left',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'vertical' => 'Vertical',
						'horizontal' => 'Horizontal',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => 'vertical',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5f5d6d786c6d6',
					'label' => 'Headline',
					'name' => 'headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f5d6d8f6c6d7',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'gif, png, jpg, webp, svg',
				),
				array(
					'key' => 'field_5f5d6da26c6d8',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5f5d6dc16c6d9',
					'label' => 'Link URL',
					'name' => 'link_url',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5b60ec726011e',
	'title' => 'Gallery',
	'fields' => array(
		array(
			'key' => 'field_5b60ec784cf45',
			'label' => 'Images',
			'name' => 'image_grid',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'prepend',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'gif, png, jpg, jpeg, webp, svg',
			'return_format' => 'array',
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '1104',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_583243bb8c402',
	'title' => 'Home Page',
	'fields' => array(
		array(
			'key' => 'field_5e07a36141d1e',
			'label' => 'Desktop Banner Links',
			'name' => 'homepage_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 12,
			'layout' => 'row',
			'button_label' => 'Add Link',
			'sub_fields' => array(
				array(
					'key' => 'field_5e07a37541d1f',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_5b3447b4ce6d5',
			'label' => 'About Me',
			'name' => 'homepage_about',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5b344836ce6d6',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'gif, png, jpg, jpeg, webp, svg',
				),
				array(
					'key' => 'field_5b344885ce6d7',
					'label' => 'Content',
					'name' => 'text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_583243bbabd96',
	'title' => 'Project Grid',
	'fields' => array(
		array(
			'key' => 'field_57644056dc159',
			'label' => 'Select Projects',
			'name' => 'project_grid',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'design',
				1 => 'post',
				2 => 'page',
			),
			'taxonomy' => array(
			),
			'filters' => array(
				0 => 'post_type',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '638',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_583243bbb167e',
	'title' => 'Projects',
	'fields' => array(
		array(
			'key' => 'field_5af3bab5895bc',
			'label' => 'Banner',
			'name' => 'project_header',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5af3bb06895be',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5af3bac6895bd',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'gif, png, jpg, jpeg, mp4, ogg, webm',
				),
			),
		),
		array(
			'key' => 'field_583270b4f3b06',
			'label' => 'Project Details',
			'name' => 'project_deets',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 1,
			'layout' => 'row',
			'button_label' => 'Populate Table',
			'sub_fields' => array(
				array(
					'key' => 'field_583270fcf3b07',
					'label' => 'Month/Year Start',
					'name' => 'proj_start',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'F Y',
					'return_format' => 'F Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5833baadc5829',
					'label' => 'Month/Year End',
					'name' => 'proj_end',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'F Y',
					'return_format' => 'F Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5832749af3b08',
					'label' => 'Roles',
					'name' => 'proj_roles',
					'type' => 'checkbox',
					'instructions' => 'Check all that apply',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'graphic' => 'Graphic Design',
						'web' => 'Web Design',
						'logo' => 'Logo Design',
						'frontend' => 'Front-end Development',
						'branding' => 'Branding',
						'print' => 'Print Design',
						'poster' => 'Poster Design',
						'tshirt' => 'T-shirt Design',
					),
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'label',
					'allow_custom' => 0,
					'save_custom' => 0,
				),
				array(
					'key' => 'field_583277bc64c82',
					'label' => 'Employer',
					'name' => 'proj_employer',
					'type' => 'text',
					'instructions' => 'Hyperlinking allowed',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'one, <a>two</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5833b548b39b2',
					'label' => 'Client',
					'name' => 'proj_client',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '<a>client</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5832785264c83',
					'label' => 'Coding Languages',
					'name' => 'proj_code',
					'type' => 'checkbox',
					'instructions' => 'Check all that apply',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'horizontal',
					'choices' => array(
						'html' => 'HTML',
						'haml' => 'HAML',
						'jade' => 'Jade',
						'css' => 'CSS',
						'bootstrap' => 'Bootstrap',
						'less' => 'LESS',
						'sass' => 'Sass/SCSS',
						'javascript' => 'JavaScript',
						'jquery' => 'jQuery',
						'php' => 'PHP',
						'twig' => 'Twig',
						'wordpress' => 'WordPress',
						'ee' => 'ExpressionEngine',
						'craft' => 'Craft',
						'kirby' => 'Kirby',
						'joomla' => 'Joomla',
						'git' => 'Git',
					),
					'default_value' => array(
					),
					'allow_custom' => 0,
					'save_custom' => 0,
					'toggle' => 0,
					'return_format' => 'label',
				),
				array(
					'key' => 'field_58327a94ef9b9',
					'label' => 'Team',
					'name' => 'proj_team',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Bethany Heck, <a>Agency</a>, etc.',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5833b458b39b0',
					'label' => 'Photographer',
					'name' => 'proj_photog',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '<a>photographer</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5833b4ebb39b1',
					'label' => 'Printer',
					'name' => 'proj_printer',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '<a>printer</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5761f8c09e4c5',
			'label' => 'Section Builder (Legacy)',
			'name' => 'project_specs',
			'type' => 'flexible_content',
			'instructions' => 'Details of the project',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'583f7c10d1e9b' => array(
					'key' => '583f7c10d1e9b',
					'name' => 'detail_text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_583f7c22d1e9c',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'default_value' => '',
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'590b9f510171a' => array(
					'key' => '590b9f510171a',
					'name' => 'detail_text_image',
					'label' => 'Text & Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_590b9f690171b',
							'label' => 'Content',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_590ba1ef0171c',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '.5',
							'mime_types' => 'gif, png, jpg, jpeg, webp, svg',
						),
						array(
							'key' => 'field_590ba2440171d',
							'label' => 'Reverse Order',
							'name' => 'reverse',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'message' => 'Image on the left, Content on the right',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Reversed',
							'ui_off_text' => 'Standard',
						),
					),
					'min' => '',
					'max' => '',
				),
				'583e4762082ad' => array(
					'key' => '583e4762082ad',
					'name' => 'detail_image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_590ba3340171e',
							'label' => 'Image Display',
							'name' => 'display',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'standard' => 'Standard',
								'wide' => 'No Padding',
								'fixed' => 'Fixed Background',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_583e482bc6ec1',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'large',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => 1,
							'mime_types' => 'gif, png, jpg, jpeg, webp, svg',
						),
					),
					'min' => '',
					'max' => '',
				),
				'590ba4a4d3285' => array(
					'key' => '590ba4a4d3285',
					'name' => 'detail_blockquote',
					'label' => 'Blockquote',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_590ba4d7d3286',
							'label' => 'Content',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5b3061bdd0c32',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'Upload image to change blockquote layout, leave empty to use default.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, png, jpg, jpeg, webp, svg',
						),
						array(
							'key' => 'field_5b306354aa2c3',
							'label' => 'Cite',
							'name' => 'cite',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '<cite>',
							'append' => '</cite>',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'583f791cd1e99' => array(
					'key' => '583f791cd1e99',
					'name' => 'detail_gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_583f79ccd1e9a',
							'label' => 'Images',
							'name' => 'images',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => 2,
							'max' => 20,
							'insert' => 'append',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '.75',
							'mime_types' => 'gif, png, jpg, jpeg, webp, svg',
							'return_format' => 'array',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Section',
			'min' => 0,
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5a5af8043b4ad',
	'title' => 'Resume',
	'fields' => array(
		array(
			'key' => 'field_5a5af9921f024',
			'label' => 'Resume Skills',
			'name' => 'resume',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5a5af9b41f025',
					'label' => 'Label',
					'name' => 'resume_label',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5a5af9ce1f026',
					'label' => 'Skill',
					'name' => 'resume_skill',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '1014',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5f7d16b9e1feb',
	'title' => 'Section Builder',
	'fields' => array(
		array(
			'key' => 'field_5f7d16c7ab5d6',
			'label' => 'Sections',
			'name' => 'sections',
			'type' => 'flexible_content',
			'instructions' => 'My version of a <b>Page Builder</b><br/>
<a href="https://github.com/OneMohrTime/onemohrtime-theme" target="_blank">Documentation</a>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5f7d16f3b0a78' => array(
					'key' => 'layout_5f7d16f3b0a78',
					'name' => 'text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1796ab5d8',
							'label' => 'Headline',
							'name' => 'headline',
							'type' => 'text',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d17acab5d9',
							'label' => 'Subheadline',
							'name' => 'subheadline',
							'type' => 'text',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d1780ab5d7',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => 'Regular body copy. Check <code>Is Large</code> to increase to larger copy size.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d17dcab5da',
							'label' => 'Button',
							'name' => 'button',
							'type' => 'link',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '67',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f7d190046a1c',
							'label' => 'Is Large',
							'name' => 'is_large',
							'type' => 'checkbox',
							'instructions' => 'Will increase section text size',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d195446a1d' => array(
					'key' => 'layout_5f7d195446a1d',
					'name' => 'text_image',
					'label' => 'Text + Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d198446a1f',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1a6346a21',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, png, jpg, webp, svg',
						),
						array(
							'key' => 'field_5f7d19dc46a20',
							'label' => 'Reverse Layout',
							'name' => 'reverse',
							'type' => 'true_false',
							'instructions' => 'Changes layout to image on the left, text on the right',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d196446a1e' => array(
					'key' => 'layout_5f7d196446a1e',
					'name' => 'image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1ac746a23',
							'label' => 'Layout',
							'name' => 'layout',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'standard' => 'Standard',
								'wide' => 'No Padding',
								'fixed' => 'Fixed Background',
							),
							'default_value' => 'standard',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f7d1a8a46a22',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'Also works with link to <code>media file</code>',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, png, jpg, webp, svg',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1fe145f73' => array(
					'key' => 'layout_5f7d1fe145f73',
					'name' => 'video',
					'label' => 'Video',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d22b57ea21',
							'label' => 'Headline',
							'name' => 'headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d22bc7ea22',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1fe745f74',
							'label' => 'Layout',
							'name' => 'layout',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'url' => 'URL (YouTube, Vimeo, etc)',
								'external' => 'Embed Code',
								'internal' => 'Internal Upload',
							),
							'default_value' => 'url',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f7d209345f75',
							'label' => 'Embed',
							'name' => 'embed',
							'type' => 'oembed',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f7d1fe745f74',
										'operator' => '==',
										'value' => 'url',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'width' => '',
							'height' => '',
						),
						array(
							'key' => 'field_5f7d21a7ddb94',
							'label' => 'Script',
							'name' => 'script',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f7d1fe745f74',
										'operator' => '==',
										'value' => 'external',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => '',
						),
						array(
							'key' => 'field_5f7d21f1ddb95',
							'label' => 'Upload',
							'name' => 'upload',
							'type' => 'file',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f7d1fe745f74',
										'operator' => '==',
										'value' => 'internal',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'mov, mp4, ogg, webm',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1c0403b04' => array(
					'key' => 'layout_5f7d1c0403b04',
					'name' => 'blockquote',
					'label' => 'Blockquote',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1cae03b06',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1c7103b05',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'Upload image to change blockquote layout, leave empty to use default.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, png, jpg, webp, svg',
						),
						array(
							'key' => 'field_5f7d1cf603b07',
							'label' => 'Cited by',
							'name' => 'cite',
							'type' => 'text',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '&lt;cite&gt;',
							'append' => '&lt;/cite&gt;',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1d9afbbc2' => array(
					'key' => 'layout_5f7d1d9afbbc2',
					'name' => 'gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1dd9fbbc4',
							'label' => 'Headline',
							'name' => 'headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d1df0fbbc5',
							'label' => 'Subheadline',
							'name' => 'subheadline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d1df6fbbc6',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1dadfbbc3',
							'label' => 'Images',
							'name' => 'images',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'insert' => 'append',
							'library' => 'all',
							'min' => 2,
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, png, jpg, webp, svg',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1e3545f6c' => array(
					'key' => 'layout_5f7d1e3545f6c',
					'name' => 'cards',
					'label' => 'Cards',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1e7b45f6d',
							'label' => 'Card Layout',
							'name' => 'card_layout',
							'type' => 'radio',
							'instructions' => 'Vertical: Image on top
Horizontal: Image on left',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'vertical' => 'Vertical',
								'horizontal' => 'Horizontal',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 'vertical',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f7d1f0f45f6e',
							'label' => 'Cards',
							'name' => 'cards',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5f7d1f1845f6f',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Card',
							'sub_fields' => array(
								array(
									'key' => 'field_5f83bb698352b',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => 'gif, png, jpg, webp, svg',
								),
								array(
									'key' => 'field_5f7d1f1845f6f',
									'label' => 'Headline',
									'name' => 'headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5f7d1f3b45f70',
									'label' => 'Subheadline',
									'name' => 'subheadline',
									'type' => 'text',
									'instructions' => 'Optional',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5f7d1f5c45f71',
									'label' => 'Text',
									'name' => 'text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'basic',
									'media_upload' => 0,
									'delay' => 0,
								),
								array(
									'key' => 'field_5f7d1f8945f72',
									'label' => 'Button',
									'name' => 'button',
									'type' => 'link',
									'instructions' => 'Optional',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Section builder used on multiple "page builder" layouts',
));

acf_add_local_field_group(array(
	'key' => 'group_5b3799d77260c',
	'title' => 'Site Options',
	'fields' => array(
		array(
			'key' => 'field_5b379a4c81e95',
			'label' => 'About This Site',
			'name' => 'site_about',
			'type' => 'wysiwyg',
			'instructions' => 'For footer; describe the plugins and components that the site was built with.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));
