<?php

// THIS IS IMPORTANT
//
// Remember to remove the encapsulating `if` statement
// from the ACF PHP export
//

acf_add_local_field_group( array(
	'key' => 'group_5e80d898b45f4',
	'title' => 'About',
	'fields' => array(
		array(
			'key' => 'field_5e80d975f7285',
			'label' => 'Subtitle',
			'name' => 'subtitle',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e80dd827a7e6',
			'label' => 'Personality Traits',
			'name' => 'personality_traits',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_5e80ddb97a7e7',
					'label' => 'Test Name',
					'name' => 'test_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Myers-Briggs',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5e80dd827a7e6',
				),
				array(
					'key' => 'field_5e80de0e7a7e9',
					'label' => 'Answer',
					'name' => 'answer',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'ENTP',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5e80dd827a7e6',
				),
				array(
					'key' => 'field_5e80de3d7a7ea',
					'label' => 'Answer Link',
					'name' => 'answer_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_5e80dd827a7e6',
				),
			),
		),
		array(
			'key' => 'field_5e80db80f7286',
			'label' => 'Work History',
			'name' => 'work_history',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5e80db9df7287',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Job',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_5e80db9df7287',
					'label' => 'Company',
					'name' => 'company',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5e80db80f7286',
				),
				array(
					'key' => 'field_5e80dbabf7288',
					'label' => 'Website',
					'name' => 'website',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_5e80db80f7286',
				),
				array(
					'key' => 'field_5e80dbb8f7289',
					'label' => 'Job Title',
					'name' => 'job_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5e80db80f7286',
				),
				array(
					'key' => 'field_5e80dbe3f728a',
					'label' => 'Job Description',
					'name' => 'job_description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'parent_repeater' => 'field_5e80db80f7286',
				),
				array(
					'key' => 'field_5e80dc09f728b',
					'label' => 'Start Date',
					'name' => 'start_date',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
					'parent_repeater' => 'field_5e80db80f7286',
				),
				array(
					'key' => 'field_5e80dc52f728c',
					'label' => 'End Date',
					'name' => 'end_date',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
					'parent_repeater' => 'field_5e80db80f7286',
				),
			),
		),
		array(
			'key' => 'field_5e80dca97a7e2',
			'label' => 'Education',
			'name' => 'education',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5e80dcbd7a7e3',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add School',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_5e80dcbd7a7e3',
					'label' => 'School Name',
					'name' => 'school_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5e80dca97a7e2',
				),
				array(
					'key' => 'field_5e80dcda7a7e4',
					'label' => 'School Website',
					'name' => 'school_website',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_5e80dca97a7e2',
				),
				array(
					'key' => 'field_5e80dd5d7a7e5',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'parent_repeater' => 'field_5e80dca97a7e2',
				),
				array(
					'key' => 'field_5f5d6c333682a',
					'label' => 'Start Date',
					'name' => 'start_date',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
					'parent_repeater' => 'field_5e80dca97a7e2',
				),
				array(
					'key' => 'field_5f5d6c553682b',
					'label' => 'End Date',
					'name' => 'end_date',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/Y',
					'return_format' => 'm/Y',
					'first_day' => 0,
					'parent_repeater' => 'field_5e80dca97a7e2',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '3018',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Almost similar to a Résumé set of fields',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_5b60ec726011e',
	'title' => 'Gallery',
	'fields' => array(
		array(
			'key' => 'field_5b60ec784cf45',
			'label' => 'Images',
			'name' => 'image_grid',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => 'These images need captions, since their FancyBox layout is different than the others',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
			'insert' => 'prepend',
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '1104',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_621bbc0e3a954',
	'title' => 'Headings',
	'fields' => array(
		array(
			'key' => 'field_621bbc1394e7e',
			'label' => 'Headline',
			'name' => 'heading_headline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => 'Leave blank to use post title',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_621bbc2f94e7f',
			'label' => 'Subheadline',
			'name' => 'subheadline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page',
				'operator' => '!=',
				'value' => '620',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Page headlines',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_583243bb8c402',
	'title' => 'Home Page Banner',
	'fields' => array(
		array(
			'key' => 'field_6510cf48fd437',
			'label' => 'Banner Tagline',
			'name' => 'homepage_tagline',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 1,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6505ed6103740',
			'label' => 'Banner CTA\'s',
			'name' => 'homepage_ctas',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 2,
			'max' => 4,
			'collapsed' => 'field_6505edd003741',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6505edd003741',
					'label' => 'Headline',
					'name' => 'headline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6505ed6103740',
				),
				array(
					'key' => 'field_6505ee3b03743',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_6505ed6103740',
				),
				array(
					'key' => 'field_6505ee0303742',
					'label' => 'Body',
					'name' => 'body',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'parent_repeater' => 'field_6505ed6103740',
				),
				array(
					'key' => 'field_6505ee5d03744',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
						1 => 'page',
						2 => 'design',
					),
					'post_status' => '',
					'taxonomy' => '',
					'allow_archives' => 0,
					'multiple' => 0,
					'allow_null' => 0,
					'parent_repeater' => 'field_6505ed6103740',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'discussion',
		2 => 'comments',
		3 => 'slug',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'categories',
		8 => 'tags',
		9 => 'send-trackbacks',
	),
	'active' => true,
	'description' => 'Home (front) page fields',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_6505f07ff108d',
	'title' => 'Home Page Content',
	'fields' => array(
		array(
			'key' => 'field_6505f080667ec',
			'label' => 'Case Studies',
			'name' => 'case_studies',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6505f0ca667ed',
					'label' => 'Headline',
					'name' => 'headline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6505f0dc667ee',
					'label' => 'Body',
					'name' => 'body',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_6505f0f4667ef',
					'label' => 'Projects',
					'name' => 'projects',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
						1 => 'page',
						2 => 'design',
					),
					'post_status' => '',
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
					),
					'return_format' => 'object',
					'min' => '',
					'max' => 5,
					'elements' => '',
				),
			),
		),
		array(
			'key' => 'field_65106c92873a4',
			'label' => 'Feature 1',
			'name' => 'feature_1',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Highlight a post, page, or project',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6531d73d34324',
					'label' => 'Headline',
					'name' => 'headline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6531d78234325',
					'label' => 'Subheadline',
					'name' => 'subheadline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6531d79934326',
					'label' => 'Body',
					'name' => 'body',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_6531d7c134327',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
					'library' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_6531d83334328',
					'label' => 'Link URL',
					'name' => 'link_url',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
				),
			),
		),
		array(
			'key' => 'field_65106d04873a7',
			'label' => 'Contact',
			'name' => 'contact',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'The button is generated automatically, since there was no way to add <code>data-module-contact-form</code>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_65106d27873a8',
					'label' => 'Headline',
					'name' => 'headline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_65106d34873a9',
					'label' => 'Body',
					'name' => 'body',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_6531d86134329',
			'label' => 'Feature 2',
			'name' => 'feature_2',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Highlight a post, page, or project',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6531d8613432a',
					'label' => 'Headline',
					'name' => 'headline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6531d8613432b',
					'label' => 'Subheadline',
					'name' => 'subheadline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6531d8613432c',
					'label' => 'Body',
					'name' => 'body',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_6531d8613432d',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_6531d8613432e',
					'label' => 'Link URL',
					'name' => 'link_url',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_65106da28f902',
			'label' => 'Additional Links',
			'name' => 'additional_links',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 4,
			'collapsed' => 'field_65106dc38f903',
			'button_label' => 'Add Card',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_65106dc38f903',
					'label' => 'Headline',
					'name' => 'headline',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_65106da28f902',
				),
				array(
					'key' => 'field_65106dd58f904',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_65106da28f902',
				),
				array(
					'key' => 'field_65106e378f905',
					'label' => 'Body',
					'name' => 'body',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
					'parent_repeater' => 'field_65106da28f902',
				),
				array(
					'key' => 'field_65106e4f8f906',
					'label' => 'Link URL',
					'name' => 'link_url',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'parent_repeater' => 'field_65106da28f902',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'discussion',
		2 => 'comments',
		3 => 'slug',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'categories',
		8 => 'tags',
		9 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_64ffdff8e0c7f',
	'title' => 'Logo Details',
	'fields' => array(
		array(
			'key' => 'field_64ffdffa40508',
			'label' => 'Full Project Link',
			'name' => 'full_project_link',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'logo',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'discussion',
		1 => 'comments',
		2 => 'author',
		3 => 'format',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_583243bbabd96',
	'title' => 'Project Grid',
	'fields' => array(
		array(
			'key' => 'field_57644056dc159',
			'label' => 'Select Projects',
			'name' => 'project_grid',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'design',
				1 => 'post',
				2 => 'page',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '638',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Select certain design projects to be featured',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_583243bbb167e',
	'title' => 'Projects',
	'fields' => array(
		array(
			'key' => 'field_5af3bab5895bc',
			'label' => 'Banner',
			'name' => 'project_header',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5af3bb06895be',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5af3bac6895bd',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif, mp4, ogg, webm',
					'preview_size' => 'medium',
				),
			),
		),
		array(
			'key' => 'field_583270b4f3b06',
			'label' => 'Project Details',
			'name' => 'project_deets',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 1,
			'layout' => 'row',
			'button_label' => 'Populate Table',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_583270fcf3b07',
					'label' => 'Month/Year Start',
					'name' => 'proj_start',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'F Y',
					'return_format' => 'F Y',
					'first_day' => 1,
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_5833baadc5829',
					'label' => 'Month/Year End',
					'name' => 'proj_end',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'F Y',
					'return_format' => 'F Y',
					'first_day' => 1,
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_5832749af3b08',
					'label' => 'Roles',
					'name' => 'proj_roles',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => 'Check all that apply',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'graphic' => 'Graphic Design',
						'web' => 'Web Design',
						'logo' => 'Logo Design',
						'frontend' => 'Front-end Development',
						'branding' => 'Branding',
						'print' => 'Print Design',
						'poster' => 'Poster Design',
						'tshirt' => 'T-shirt Design',
					),
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'label',
					'allow_custom' => 0,
					'save_custom' => 0,
					'custom_choice_button_text' => 'Add new choice',
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_583277bc64c82',
					'label' => 'Employer',
					'name' => 'proj_employer',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Hyperlinking allowed',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'one, <a>two</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_5833b548b39b2',
					'label' => 'Client',
					'name' => 'proj_client',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '<a>client</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_5832785264c83',
					'label' => 'Coding Languages',
					'name' => 'proj_code',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => 'Check all that apply',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'horizontal',
					'choices' => array(
						'html' => 'HTML',
						'haml' => 'HAML',
						'jade' => 'Jade',
						'css' => 'CSS',
						'bootstrap' => 'Bootstrap',
						'less' => 'LESS',
						'sass' => 'Sass/SCSS',
						'javascript' => 'JavaScript',
						'jquery' => 'jQuery',
						'php' => 'PHP',
						'twig' => 'Twig',
						'wordpress' => 'WordPress',
						'ee' => 'ExpressionEngine',
						'craft' => 'Craft',
						'kirby' => 'Kirby',
						'joomla' => 'Joomla',
						'git' => 'Git',
					),
					'default_value' => array(
					),
					'allow_custom' => 0,
					'save_custom' => 0,
					'toggle' => 0,
					'return_format' => 'label',
					'custom_choice_button_text' => 'Add new choice',
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_58327a94ef9b9',
					'label' => 'Team',
					'name' => 'proj_team',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Bethany Heck, <a>Agency</a>, etc.',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_5833b458b39b0',
					'label' => 'Photographer',
					'name' => 'proj_photog',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '<a>photographer</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_583270b4f3b06',
				),
				array(
					'key' => 'field_5833b4ebb39b1',
					'label' => 'Printer',
					'name' => 'proj_printer',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '<a>printer</a>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_583270b4f3b06',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Custom project banners and details',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_5f7d16b9e1feb',
	'title' => 'Section Builder',
	'fields' => array(
		array(
			'key' => 'field_5f7d16c7ab5d6',
			'label' => 'Sections',
			'name' => 'sections',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => 'My version of a <b>Page Builder</b><br/>
<a href="https://github.com/OneMohrTime/onemohrtime-theme" target="_blank">Documentation</a>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5f7d16f3b0a78' => array(
					'key' => 'layout_5f7d16f3b0a78',
					'name' => 'text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1796ab5d8',
							'label' => 'Headline',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d17acab5d9',
							'label' => 'Subheadline',
							'name' => 'subheadline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d1780ab5d7',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Regular body copy. Check <code>Is Large</code> to increase to larger copy size.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d17dcab5da',
							'label' => 'Button',
							'name' => 'button',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '67',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5f7d190046a1c',
							'label' => 'Increase Size',
							'name' => 'is_large',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => 'Increase section\'s text size',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'true' => 'Large Text',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d195446a1d' => array(
					'key' => 'layout_5f7d195446a1d',
					'name' => 'text_image',
					'label' => 'Text + Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d198446a1f',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1a6346a21',
							'label' => 'Image',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_5f7d19dc46a20',
							'label' => 'Reverse Layout',
							'name' => 'reverse',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => 'Changes layout to image on the left, text on the right',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Image Left',
							'ui_off_text' => 'Image Right',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d196446a1e' => array(
					'key' => 'layout_5f7d196446a1e',
					'name' => 'image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1ac746a23',
							'label' => 'Layout',
							'name' => 'layout',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'standard' => 'Standard',
								'wide' => 'No Padding',
								'fixed' => 'Fixed Background',
							),
							'default_value' => 'standard',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f7d1a8a46a22',
							'label' => 'Image',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => 'Checking <i>Link to Image</i> checkbox links image directly to <code>media file</code>.

Looking for text for this module? Add a <i>Text</i> module above, and	the spacing will work out.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_6030ac3f6b329',
							'label' => 'Link to File',
							'name' => 'link_to_file',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => 'Insert a link directly to the image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Linked',
							'ui_off_text' => 'Unlinked',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1fe145f73' => array(
					'key' => 'layout_5f7d1fe145f73',
					'name' => 'video',
					'label' => 'Video / Audio / Embeds',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d22b57ea21',
							'label' => 'Headline',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d22bc7ea22',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1fe745f74',
							'label' => 'Layout',
							'name' => 'layout',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'url' => 'URL (YouTube, Vimeo, etc)',
								'external' => 'Embed Code',
								'internal' => 'Internal Upload',
							),
							'default_value' => 'url',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f7d209345f75',
							'label' => 'Embed',
							'name' => 'embed',
							'aria-label' => '',
							'type' => 'oembed',
							'instructions' => 'Paste a YouTube, Vimeo, or similar oEmbed link',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f7d1fe745f74',
										'operator' => '==',
										'value' => 'url',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'width' => '',
							'height' => '',
						),
						array(
							'key' => 'field_5f7d21a7ddb94',
							'label' => 'Script',
							'name' => 'script',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => 'Paste the entire embed script',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f7d1fe745f74',
										'operator' => '==',
										'value' => 'external',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => '',
						),
						array(
							'key' => 'field_5f7d21f1ddb95',
							'label' => 'Upload',
							'name' => 'upload',
							'aria-label' => '',
							'type' => 'file',
							'instructions' => 'Upload video or audio',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f7d1fe745f74',
										'operator' => '==',
										'value' => 'internal',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'mov, mp4, ogg, webm, mp3, wav',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1c0403b04' => array(
					'key' => 'layout_5f7d1c0403b04',
					'name' => 'blockquote',
					'label' => 'Blockquote',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1cae03b06',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1c7103b05',
							'label' => 'Image',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => 'Upload image to change blockquote layout, leave empty to use default.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_5f7d1cf603b07',
							'label' => 'Cited by',
							'name' => 'cite',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Optional',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '&lt;cite&gt;',
							'append' => '&lt;/cite&gt;',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1d9afbbc2' => array(
					'key' => 'layout_5f7d1d9afbbc2',
					'name' => 'gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1dd9fbbc4',
							'label' => 'Headline',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d1df0fbbc5',
							'label' => 'Subheadline',
							'name' => 'subheadline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f7d1df6fbbc6',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5f7d1dadfbbc3',
							'label' => 'Images',
							'name' => 'images',
							'aria-label' => '',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min' => 2,
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
							'insert' => 'append',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f9ced51b47be' => array(
					'key' => 'layout_5f9ced51b47be',
					'name' => 'code',
					'label' => 'Code Snippet',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f9df128b085c',
							'label' => 'Language',
							'name' => 'language',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Adds Prism.js syntax highlighting',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'javascript|zsh|scss|etc..',
							'prepend' => '.language-',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f9cedccb47bf',
							'label' => 'Snippet',
							'name' => 'snippet',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => 'Spaces seem to work better than tabs here',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 5,
							'new_lines' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f7d1e3545f6c' => array(
					'key' => 'layout_5f7d1e3545f6c',
					'name' => 'cards',
					'label' => 'Cards',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f7d1e7b45f6d',
							'label' => 'Card Layout',
							'name' => 'card_layout',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '<b>Default:</b> Image on top<br/>
<b>Flag:</b> Image on left',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'vertical' => 'Default',
								'horizontal' => 'Flag',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 'vertical',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f7d1f0f45f6e',
							'label' => 'Cards',
							'name' => 'cards',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5f7d1f1845f6f',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Card',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_5f83bb698352b',
									'label' => 'Image',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_5f7d1f0f45f6e',
								),
								array(
									'key' => 'field_5f7d1f1845f6f',
									'label' => 'Headline',
									'name' => 'headline',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '60',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'parent_repeater' => 'field_5f7d1f0f45f6e',
								),
								array(
									'key' => 'field_5f7d1f3b45f70',
									'label' => 'Subheadline',
									'name' => 'subheadline',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => 'Optional',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '40',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'parent_repeater' => 'field_5f7d1f0f45f6e',
								),
								array(
									'key' => 'field_5f7d1f5c45f71',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
									'parent_repeater' => 'field_5f7d1f0f45f6e',
								),
								array(
									'key' => 'field_5f7d1f8945f72',
									'label' => 'Button',
									'name' => 'button',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => 'Optional',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'parent_repeater' => 'field_5f7d1f0f45f6e',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Section builder used on multiple "page builder" layouts',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_5b3799d77260c',
	'title' => 'Site Globals',
	'fields' => array(
		array(
			'key' => 'field_651e45803946a',
			'label' => 'Site Settings',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_651e4372f7405',
			'label' => 'Site Alert',
			'name' => 'site_alert',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_651e452a39469',
					'label' => 'Show Alert',
					'name' => 'show_alert',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => 'Show',
					'ui_off_text' => 'Hide',
					'ui' => 1,
				),
				array(
					'key' => 'field_651e4394f7406',
					'label' => 'Alert Text',
					'name' => 'alert_text',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 1,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_651e43c8f7407',
					'label' => 'Alert Link',
					'name' => 'alert_link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_623bfc58c3ff9',
			'label' => 'Availability',
			'name' => 'availability',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '<b>Open:</b> I’m actively looking for new projects to design<br/>
<b>Busy:</b> I am currently busy, but accepting future projects<br/>
<b>None:</b> I’m completely at capacity for the foreseeable future',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'open' => 'Open',
				'busy' => 'Busy',
				'none' => 'None',
			),
			'default_value' => 'open',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_651e44832c475',
			'label' => 'Site Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_651e4335f7404',
			'label' => 'Footer Details',
			'name' => 'footer_details',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5b379a4c81e95',
			'label' => 'Footer About',
			'name' => 'site_about',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'For footer; describe the plugins and components that the site was built with.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_651e39dff7400',
			'label' => 'Footer Flags',
			'name' => 'footer_flags',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 1,
			'rows_per_page' => 5,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'sub_fields' => array(
				array(
					'key' => 'field_651e3a19f7401',
					'label' => 'Abbreviation',
					'name' => 'abbreviation',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => 2,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_651e39dff7400',
				),
				array(
					'key' => 'field_651e4295f7402',
					'label' => 'Country',
					'name' => 'country',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_651e39dff7400',
				),
				array(
					'key' => 'field_651e42c5f7403',
					'label' => 'Country Link',
					'name' => 'country_link',
					'aria-label' => '',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'post_status' => '',
					'taxonomy' => array(
						0 => 'category:travel',
					),
					'allow_archives' => 0,
					'multiple' => 0,
					'allow_null' => 0,
					'parent_repeater' => 'field_651e39dff7400',
				),
			),
		),
		array(
			'key' => 'field_6535eaaa74d44',
			'label' => 'Contact Form',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6535eac974d45',
			'label' => 'Form',
			'name' => 'form',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'wpforms',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 1,
		),
		array(
			'key' => 'field_6521bb4829f76',
			'label' => '404 Page',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6521bb5e29f77',
			'label' => 'Headline',
			'name' => 'error_headline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6521bb8029f78',
			'label' => 'Body',
			'name' => 'error_body',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_6521bbda29f79',
			'label' => 'Links',
			'name' => 'error_links',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'post',
				1 => 'page',
				2 => 'design',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'globals',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Custom settings around the site',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_623c00a565d33',
	'title' => 'Top 10 Lists',
	'fields' => array(
		array(
			'key' => 'field_6243d9530c739',
			'label' => 'Power Ranking',
			'name' => 'power_ranking',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_625106e9bc546',
			'min' => 0,
			'max' => 11,
			'layout' => 'block',
			'button_label' => 'Add Power Rankings',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_625106e9bc546',
					'label' => 'Power Ranking Item',
					'name' => 'power_ranking_item',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '80',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_6243d9530c739',
				),
				array(
					'key' => 'field_6251072cbc547',
					'label' => 'Power Ranking Link',
					'name' => 'power_ranking_link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'parent_repeater' => 'field_6243d9530c739',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'top-10',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'slug',
		6 => 'author',
		7 => 'page_attributes',
		8 => 'send-trackbacks',
	),
	'active' => true,
	'description' => 'Completely unnecessary addition to the site, mostly for argument\'s sake',
	'show_in_rest' => 1,
) );

acf_add_local_field_group( array(
	'key' => 'group_623bf4c506686',
	'title' => 'Additional Photos',
	'fields' => array(
		array(
			'key' => 'field_623bf4d346bab',
			'label' => 'Parallax Image',
			'name' => 'parallax_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '<i>Optional</i>. Taller photos produce a higher parallax effect.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'gif, jpg, jpeg, png, heic, webp, svg, avif',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
	'key' => 'group_62258c38cca1a',
	'title' => 'Related Posts',
	'fields' => array(
		array(
			'key' => 'field_62258c4459f18',
			'label' => 'Related Posts',
			'name' => 'related_posts',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_62258c6b59f19',
			'min' => 0,
			'max' => 3,
			'layout' => 'block',
			'button_label' => 'Add Related Post',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_62258c6b59f19',
					'label' => 'Related Post',
					'name' => 'related_post',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
						1 => 'page',
						2 => 'design',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'object',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 1,
					'parent_repeater' => 'field_62258c4459f18',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'design',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Choose custom pages/posts to visit next',
	'show_in_rest' => 0,
) );
